openapi: 3.0.0

info:
  description: >
    Land Cover Classification System Web Service. You can find out more about LCCS-WS at [https://github.com/brazil-data-cube/lccs-ws](https://github.com/brazil-data-cube/lccs-ws)

  version: '0.2.0'

  title: Land Cover Classification System Web Service

  contact:
    name: Fabiana Zioti
    email: fabi.zioti@gmail.com

  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'

servers:
  - url: 'https://localhost/lccs-ws'
    description: Production server


paths:

  '/classification_systems':
    get:
      tags:
        - Classification Systems
      summary: List of Classification System.
      description: Retrieve list of available classification systems.
      operationId: getClassificationSystems
      responses:
        '200':
          $ref: '#/components/responses/ClassificationSystems'
        '500':
          $ref: '#/components/responses/ServerError'

  '/classification_systems/{system_id}':
    parameters:
       - $ref: '#/components/parameters/system_id'
    get:
      tags:
        - Classification Systems
      summary: >
        Describe the classification system with id `system_id`
      description: Returns information of classification system by Id.
      operationId: describeClassificationSystem
      responses:
        '200':
          $ref: '#/components/responses/ClassificationSystem'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  '/classification_systems/{system_id}/classes':
    get:
      tags:
        - Classes
      summary: fetch classes
      description: >
        Fetch classes of the classification with id `system_id`.
      operationId: getClasses
      parameters:
        - $ref: '#/components/parameters/system_id'
      responses:
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '200':
          $ref: '#/components/responses/Classes'

  '/classification_systems/{system_id}/classes/{classe_id}':
    get:
      tags:
        - Classes
      summary: fetch a single classe
      description: >
          Fetch the classe with id `classe_id` in the classification system
          with id `system_id`.
      operationId: getClasse
      parameters:
          - $ref: '#/components/parameters/system_id'
          - $ref: '#/components/parameters/classe_id'
      responses:
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '200':
          $ref: '#/components/responses/Classe'

  '/mappings/{system_id_source}/{system_id_target}':
    get:
      tags:
        - Mappings
      summary: Retrives classification systems mappings
      description: Mapping of classification systems.
      operationId: getMapping
      parameters:
        - $ref: '#/components/parameters/system_id_source'
        - $ref: '#/components/parameters/system_id_target'
      responses:
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
        '200':
          $ref: '#/components/responses/Mappings'

components:

  #-------------------------------
  # Reusable operation parameters
  #-------------------------------

  parameters:

    system_id:
      name: system_id
      in: path
      description: Identifier (name) of a classification system
      required: true
      schema:
        type: string

    classe_id:
      name: classe_id
      in: path
      description: Identifier (name) of a class
      required: true
      schema:
        type: string

    system_id_source:
      name: system_id_source
      in: path
      description: Identifier (name) of a source classification system
      required: true
      schema:
        type: string

    system_id_target:
      name: system_id_target
      in: path
      description: Identifier (name) of a target classification system
      required: true
      schema:
        type: string


  #-------------------------------
  # Reusable schemas (data models)
  #-------------------------------

  schemas:

    classification_system:
      type: object
      required:
        - id
        - name
        - links
      properties:
        id:
          type: number
        name:
          type: string
        authority_name:
          type: string
        description:
          type: string
        version:
          type: string
        styles:
          type: array
          items:
            $ref: "#/components/schemas/link"
          example:
            - href: http://data.example.com/buildings
              rel: item
              title: Qgis
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"
          example:
            - href: http://data.example.com/buildings
              rel: item


    classification_systems:
      type: object
      required:
        - links
      properties:
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"

    classes:
      type: object
      required:
        - links
      properties:
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"

    classe:
      type: object
      required:
        - name
        - id
      properties:
        id:
          type: number
        name:
          type: string
        code:
          type: string
        description:
          type: string
        parent:
          type: object
          items:
            $ref: "#/components/schemas/classe"
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"

    mapping:
      type: object
      properties:
        links:
          type: array
          items:
            $ref: "#/components/schemas/link"
        classe_source:
          type: object
          items:
            $ref: "#/components/schemas/classe"
        classe_target:
          type: object
          items:
            $ref: "#/components/schemas/classe"
        description:
          type: string
        degree_of_similarity:
          type: number

    mappings:
      type: array
      items:
        $ref: "#/components/schemas/mapping"

    link:
      title: Link
      description: A generic link.
      type: object
      required:
        - href
        - rel
      properties:
        href:
          type: string
          format: url
          example: 'http://www.geoserver.example/stac/naip/child/catalog.json'
        rel:
          type: string
          example: child
        title:
          type: string
          example: Child

    exception:
      type: object
      description: >
        Information about the exception: an error code plus an optional description.
      required:
        - code
      properties:
        code:
          type: string
        description:
          type: string

  responses:


    ClassificationSystems:
      description: >
        The classsification systems shared by this API.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/classification_systems'

    ClassificationSystem:
      description: >
        Information about classification system id `system_id`.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/classification_system'

    Classes:
      description: >
        The response is a document consisting of classes in the classification system.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/classes'

    Classe:
      description: >
        fetch the classe with id `classe_id` in the classification system
        with id `system_id`
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/classe'


    Mappings:
      description: >
        fetch the mapping with `systemIdSource` and `systemIdTarget`.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/mappings'

    ServerError:
      description: >
        A server error occurred.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exception'
        text/html:
          schema:
            type: string

    NotFound:
      description: >
        The requested URI was not found.

    InvalidParameter:
      description: >
        A query parameter has an invalid value.